---
title: "intervalos-confianza"
author: "Isaías M. CRIP-DADSIG"
date: "2023-09-29"
output: html_document

---


```{r}
pacman::p_load( readr, tidyr, dplyr, janitor, srvyr,
                kableExtra, stringr, foreign, utils)



knitr::opts_knit$set(root.dir = 'C:/Users/ISAIS MORALES/00_conacyt/encodat-16')
setwd('C:/Users/ISAIS MORALES/00_conacyt/encodat-16')
pth <- './datos/datos-originales/'

df_hog <- read.csv( paste0(pth, 'ENCODAT_2016_2017_Hogar.csv') , sep= ';' )
df_ind <- readr::read_delim( paste0(pth, 'ENCODAT_2016_2017_Individual.csv'), delim = ';')


```

```{r}

df_h1 <-  df_hog %>% group_by(id_hogar) %>% summarise( tothog = n())

df_ind <- df_ind %>% mutate( id_hog = substring(id_pers, 1, 20 ) )

 
df_m <- select(df_hog,id_hogar,   est_var,  ponde_hh,  code_upm,  estrato)
 
df <-   merge(df_ind, df_m, by.x = 'id_hog'  , by.y = 'id_hogar')
```


```{r}
df_estima <- df %>% mutate( 
  di5a = as.integer(di5a),
  di5a =  ifelse(is.na(di5a), 0, di5a),
  di5a_est = ifelse( di5a == 0 , 0, 1),
  pob = 1
)

```

```{r}
dis_muest <- df_estima  %>%
  as_survey_design(ids = code_upm,
                   strata = estrato,
                   weights = ponde_ss)

```

```{r}
mar_alguna <- dis_muest %>% 
  group_by(di5a_est) %>%
  summarise( prevalencia = survey_prop ( di5a_est ,
                                         vartype = c("se", "ci"),
                                         level=0.95), proportion = TRUE) 
mar_alguna
```

```{r}
# Filtrado únicamente de los que sí han consumido 
mar_alguna <- mar_alguna[2, ]
mar_alguna$prevalencia * 100
mar_alguna$prevalencia_low * 100 
mar_alguna$prevalencia_upp* 100
```

